import type { SourceConfig } from "@rss/db";

import { DashboardShell } from "../components/DashboardShell";
import { FeedForm } from "../components/feed-form";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";

type FeedsPageProps = {
  userSlug?: string;
  feeds: SourceConfig[];
};

export function FeedsPage({ userSlug, feeds }: FeedsPageProps) {
  return (
    <DashboardShell userSlug={userSlug}>
      <div className="space-y-8">
        <div className="space-y-2">
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">
            Feeds
          </p>
          <h1 className="text-3xl font-semibold">Manage your sources</h1>
          <p className="max-w-2xl text-muted-foreground">
            Add RSS feeds or Google search queries. Everything stays scoped to your account and
            powers the reports generated by the pipeline.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Add a new feed</CardTitle>
          </CardHeader>
          <CardContent>
            <FeedForm onRefresh={() => window.location.reload()} />
          </CardContent>
        </Card>

        <div className="space-y-4">
          <h2 className="text-lg font-semibold">Existing feeds</h2>
          {feeds.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No feeds yet. Create your first feed to start generating reports.
            </p>
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {feeds.map((feed) => (
                <Card key={feed.id}>
                  <CardHeader>
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <p className="text-sm font-medium uppercase tracking-wide text-primary">
                          {feed.type}
                        </p>
                        <CardTitle>{feed.name}</CardTitle>
                      </div>
                      <span className="text-xs text-muted-foreground">
                        {feed.isActive ? "Active" : "Paused"}
                      </span>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="text-sm text-muted-foreground">
                      {feed.url ? feed.url : feed.query}
                    </div>
                    <FeedForm feed={feed} onRefresh={() => window.location.reload()} />
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>
    </DashboardShell>
  );
}
