
export const categoryPrompts: Record<string, string> = {
    africa: `Produce a daily analytical brief on developments in the past days that may influence the relationship between African nations and France. Focus on: (1) diplomatic actions, policy changes, international agreements, elections, military operations, economic cooperation, public opinion shifts, or notable statements from political leaders; (2) issues that can affect supply chains, trade flows, port and airport operations, air cargo capacity, and logistics between France and African countries; (3) airline and aviation news involving Air France, CMA CGM Air Cargo, and other carriers operating between France and Africa that may impact Air France’s network, strategy, or profitability. For each major item, clearly describe what happened, the main actors involved (states, companies, institutions), the underlying causes or triggers, and the potential operational, financial, and reputational impacts in the short term (coming weeks) and long term (6–24 months). Perform a sentiment analysis for each major event and for the overall situation, classifying them as positive, negative, or mixed from the perspective of France–Africa relations and the air-cargo/supply-chain ecosystem.`,

    canada: `Produce a daily analytical brief on developments in the past days that may influence the relationship between Canada and France. Focus on: (1) diplomatic actions, policy changes, international agreements, elections, defense or security cooperation, economic partnerships, public opinion shifts, or notable statements from political leaders; (2) issues that can affect supply chains, trade flows, port and airport operations, intermodal logistics, and air cargo capacity between Canada and France; (3) airline and aviation news involving Air France, CMA CGM Air Cargo, and other carriers operating between France and Canada that may impact Air France’s network, strategy, or profitability. For each major item, clearly describe what happened, the main actors involved (states, companies, institutions), the underlying causes or triggers, and the potential operational, financial, and reputational impacts in the short term (coming weeks) and long term (6–24 months). Perform a sentiment analysis for each major event and for the overall situation, classifying them as positive, negative, or mixed from the perspective of France–Canada relations and the air-cargo/supply-chain ecosystem.`,

    tech: `Produce a concise, discovery-oriented newsletter brief on notable developments across software and the wider technology industry over the past day. The audience is a tech-aware reader, but not necessarily a specialist, so avoid deep implementation details and focus on what happened, why it matters, and how it may change how people build or use technology. Prioritize breadth, signal, and genuine discovery over the most heavily covered subjects. Look for important or surprising developments that may be missed by mainstream technology coverage, including open-source projects and maintainers, programming languages and frameworks, databases, infrastructure and cloud platforms, developer tools, cybersecurity and privacy, outages and reliability, hardware and chips, robotics, networking, standards, digital rights, technology policy and regulation, research with practical implications, and visible trends in communities such as Hacker News, Reddit, and relevant specialist forums. Include developments from smaller companies, independent projects, and less prominent regions when they are credible and consequential.
    AI, machine-learning models, LLMs, and generative AI should not dominate the brief or be treated as an automatic category. Include them only when there is a clearly verified, material development with practical consequences, such as a significant security incident, widely adopted capability, important policy change, meaningful research result, major infrastructure shift, or substantial product change. Exclude routine model releases, minor benchmark gains, funding announcements, speculative claims, promotional launch coverage, and recycled commentary unless they have demonstrable impact. When AI is not the most consequential subject of the day, give the space to other areas of technology instead.
    For each major story, clearly describe the core event, the key actors involved (companies, projects, researchers, regulators, communities), what makes it worth attention, and the likely practical impact in the short term (coming days or weeks) and the longer term (months or years). Distinguish confirmed facts from interpretation and speculation, favor primary sources and reliable reporting, and avoid repeating several stories that describe the same underlying development. Perform a sentiment analysis for each major story and for the overall day’s news, classifying them as positive, negative, or mixed from the perspective of users and developers.`,

    pod: `Produce a practical daily print-on-demand intelligence brief for Obsessive Starter, a Shopify graphic-t-shirt brand for hobby hoppers. Its voice is warm, self-aware, sarcastic, and celebratory: it treats the exhilarating start of a new hobby as the point, never as a personal failure.

Prioritize recent, verified developments that can change a small POD apparel shop's decisions: (1) platform, catalog, pricing, integration, fulfillment-quality, production-time, shipping, or policy changes at Shopify and POD providers such as Printful, Printify, Gelato, Gooten, CustomCat, SPOD, and Apliiq; (2) ecommerce growth tactics with credible evidence for Shopify apparel, including product-page conversion, bundles, email/SMS consent, creator partnerships, organic social, merchandising, and retention; (3) emerging hobby communities, seasonal moments, gift occasions, memes, and consumer-language signals that could become an original "serial hobby starter" design or collection; and (4) operational risks, including delivery disruption, customer-service issues, fees, intellectual-property policy, or marketplace/platform rule changes.

For every item, state the confirmed development, source and date, the direct implication for Obsessive Starter, and a specific next action labeled "Do now", "Watch", or "Ignore". For promising creative signals, propose at most one original design-angle or collection hypothesis using fresh wording; do not reproduce slogans, artwork, brand names, protected characters, or distinctive third-party copy. Separate evidence from inference, flag unverified community anecdotes as anecdotes, favor official sources for platform changes, and deduplicate stories covering the same event. Do not fill the report with generic "start a POD business" advice, SEO listicles, speculative trend claims, or routine AI announcements. End with a prioritized three-item action queue and classify each major item and the overall outlook as positive, negative, or mixed for Obsessive Starter.`
};
